// <auto-generated />
using CapitoYuliana_ExamenProgreso1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapitoYuliana_ExamenProgreso1.Migrations
{
    [DbContext(typeof(CapitoYuliana_ExamenProgreso1Context))]
    [Migration("20241030205738_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapitoYuliana_ExamenProgreso1.Models.Capito", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cedula"));

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MayorDeEdad")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("celularId")
                        .HasColumnType("int");

                    b.Property<int>("idCelular")
                        .HasColumnType("int");

                    b.HasKey("Cedula");

                    b.HasIndex("celularId");

                    b.ToTable("Capito");
                });

            modelBuilder.Entity("CapitoYuliana_ExamenProgreso1.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("CapitoYuliana_ExamenProgreso1.Models.Capito", b =>
                {
                    b.HasOne("CapitoYuliana_ExamenProgreso1.Models.Celular", "celular")
                        .WithMany()
                        .HasForeignKey("celularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("celular");
                });
#pragma warning restore 612, 618
        }
    }
}
